//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBazarUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order = new HashSet<Order>();
            this.ProdcutImages = new HashSet<ProdcutImages>();
        }
    
        public int ID { get; set; }
        public string Product_Name { get; set; }
        public string Producct_Short_Description { get; set; }
        public string Product_Long_Description { get; set; }
        public string Is_Active { get; set; }
        public string Is_Featured { get; set; }
        public string Is_OnSale { get; set; }
        public Nullable<int> Product_Price { get; set; }
        public Nullable<int> Product_Sale_Price { get; set; }
        public Nullable<int> Product_Quantity { get; set; }
        public string Product_Feature_Image { get; set; }
        public string Product_Size { get; set; }
        public Nullable<int> Vendor_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public string Created_By { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdcutImages> ProdcutImages { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
