//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBazarUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wishlist
    {
        public int ID { get; set; }
        public int Customer_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
